after-startup-command = [
    'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]

start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 10
inner.vertical =   10 
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus --boundaries all-monitors-outer-frame  --boundaries-action wrap-around-all-monitors left'
alt-j = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors down'
alt-k = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors up'
alt-l = 'focus --boundaries all-monitors-outer-frame  --boundaries-action wrap-around-all-monitors right'

alt-p = ['exec-and-forget open -a "Postman"', 'mode main']
alt-c = ['exec-and-forget open -a "Microsoft Teams"', 'mode main']
alt-g = ['exec-and-forget open -a "GitHub Desktop"', 'mode main']
alt-space = ['exec-and-forget open -n  -a "WezTerm"', 'mode main']
alt-b = '''exec-and-forget osascript -e '
tell application "Google Chrome"
    make new window
    activate
end tell'
'''

alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'
alt-0 = 'balance-sizes'

alt-x = 'close'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-shift-1 = ['move-node-to-workspace 1']
alt-shift-2 = ['move-node-to-workspace 2']
alt-shift-3 = ['move-node-to-workspace 3']
alt-shift-4 = ['move-node-to-workspace 4']
alt-shift-5 = ['move-node-to-workspace 5']
alt-shift-6 = ['move-node-to-workspace 6']
alt-shift-7 = ['move-node-to-workspace 7']
alt-shift-8 = ['move-node-to-workspace 8']
alt-shift-9 = ['move-node-to-workspace 9']

alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-tab = 'workspace-back-and-forth'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'


alt-f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
alt-r = ['flatten-workspace-tree', 'mode main'] # reset layout

alt-shift-semicolon = 'mode service'
[mode.service.binding]
esc = ['reload-config', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

[workspace-to-monitor-force-assignment]
1 = ['KYY', 1,2,3]
2 = ['DELL U2415','Built-in Retina Display']
3 = [3, 'KYY',2,1]
4 = [3, 'KYY',2,1]
5 = [2, 'Built-in Retina Display',2 ,1 ]
6 = [3, 'Built-in Retina Display',2 ,1 ]

# [[on-window-detected]]
# if.app-id = 'com.microsoft.teams2'
# check-further-callbacks = true
# run = ['move-node-to-workspace 1']  # The callback itself
#
# [[on-window-detected]]
# if.app-id = 'com.microsoft.Outlook'
# check-further-callbacks = true
# run = ['move-node-to-workspace 1']  # The callback itself
#
# [[on-window-detected]]
# if.app-id = 'com.github.wez.wezterm'
# check-further-callbacks = true
# run = ['move-node-to-workspace 2']  # The callback itself
# [[on-window-detected]]
# if.app-id = 'com.googlecode.iterm2'
# check-further-callbacks = true
# run = ['move-node-to-workspace 2']  # The callback itself
#
# [[on-window-detected]]
# if.app-id = 'com.google.Chrome'
# check-further-callbacks = true
# run = ['move-node-to-workspace 3']  # The callback itself
#
# [[on-window-detected]]
# if.app-id = 'com.apple.finder'
# check-further-callbacks = true
# run = ['layout floating']  # The callback itself
#
# [[on-window-detected]]
# if.app-id = 'com.postmanlabs.mac'
# check-further-callbacks = true
# run = ['move-node-to-workspace 4']  # The callback itself
#
# [[on-window-detected]]
# if.app-id = 'com.github.GitHubClient'
# check-further-callbacks = true
# run = ['move-node-to-workspace 4']  # The callback itself
#
#
# [[on-window-detected]]
# if.app-id = 'net.whatsapp.WhatsApp'
# check-further-callbacks = true
# run = ['layout floating','move-node-to-workspace 2' ]  # The callback itself
#
# [[on-window-detected]]
# if.app-id = 'com.apple.PhotoBooth'
# check-further-callbacks = true
# run = ['layout floating','move-node-to-workspace 1' ]  # The callback itself
#
#
# [[on-window-detected]]
# if.app-id = 'md.obsidian'
# run = ['layout floating'] 
#
# [[on-window-detected]]
# if.app-id = 'com.apple.iCal'
# run = ['layout floating']  
#
# [[on-window-detected]]
# if.app-id = 'com.apple.Notes'
# run = ['layout floating']  


